# Generated by Django 4.1.4 on 2023-01-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='quantity',
            new_name='Expense_amount',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='add_money',
            new_name='Type',
        ),
    ]
