# Generated by Django 4.1.4 on 2023-01-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_rename_quantity_expenses_expense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Savings_Percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
