# Generated by Django 4.1.4 on 2023-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_userprofile_savings_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Savings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
