# Generated by Django 4.1.4 on 2023-01-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_alter_userprofile_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Savings_Percentage',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
